name: "Vultr Deploy"
description: "Manages a vultr server"
inputs:
  action:
    required: true
  api_key:
    required: true
  domain:
    required: false
  os:
    required: false
  pull_request_id:
    required: true
outputs:
  ip_address:
    description: "IP address"
  default_password:
    description: "Temporary password"
  instance:
    description: "object of created instance"
runs:
  using: "node18"
  main: "dist/index.js"
