name: "Vultr Deploy"
description: "Manages a vultr server"
inputs:
  action:
    required: true
  api_key:
    required: true
  domain:
    required: true
  os_id:
    required: true
  plan:
    required: true
  pullrequest_id:
    required: true
  region:
    required: true
  tag:
    required: true
outputs:
  ip_address:
    description: "IP address"
  default_password:
    description: "Temporary password"
  instance:
    description: "object of created instance"
runs:
  using: "node12"
  main: "dist/index.js"
